INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(1,'ESTOMATOLOGÍA',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(2,'FARMACIA',true, 1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(3,'FISIOTERAPIA',true, 1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(4,'GERONTOLOGÍA',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(5,'MEDICINA',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(6,'NUTRICIÓN',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(7,'ODONTOLOGÍA',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(8,'OPTOMETRÍA',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(9,'PSICOLOGÍA',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(10,'PSICOLOGÍA CLÍNICA',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(11,'QUÍMICO BIÓLOGO PARASITÓLOGO',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(12,'QUÍMICO CLÍNICO',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(13,'QUÍMICO CLÍNICO BIÓLOGO',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(14,'QUÍMICO FARMACO BIÓLOGO',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(15,'RADIOLOGÍA E IMAGEN',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(16,'TERAPIA FÍSICA',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(17,'TRABAJO SOCIAL',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(18,'ENFERMERÍA',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(19,'DENTAL',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(20,'RADIOLOGÍA E IMAGEN',true,2);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(21,'LABORATORISTA CLÍNICO',true,2);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(22,'LABORATORISTA QUÍMICO',true,2);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(23,'TERAPIA RESPIRATORIA',true,2);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(24,'TRABAJO SOCIAL',true,2);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(25,'ENFERMERÍA',true,2);