INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(1,'Estomatología',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(2,'Farmacia',true, 1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(3,'Fisioterapia',true, 1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(4,'Gerontología',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(5,'Medicina',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(6,'Nutrición',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(7,'Odontología',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(8,'Optometría',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(9,'Psicología',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(10,'Psicología Clínica',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(11,'Químico Biólogo Parasitólogo',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(12,'Químico Clínico',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(13,'Químico Clínico Bíologo',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(14,'Químico Farmaco Biólogo',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(15,'Radiología e Imagen',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(16,'Terapia Física',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(17,'Trabajo Social',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(18,'Enfermería',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(19,'Dental',true,1);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(20,'Radiología e Imagen',true,2);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(21,'Laboratorista Clínico',true,2);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(22,'Laboratorista Químico',true,2);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(23,'Terapia Respiratoria',true,2);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(24,'Trabajo Social',true,2);
INSERT INTO carrera(id, nombre, activo, nivel_academico_id) VALUES(25,'Enfermería',true,2);
SELECT setval('carrera_id_seq', (SELECT MAX(id) from carrera));