INSERT INTO institucion(id, nombre) VALUES(1 , 'Ateneo Universitario en Humanidades y Ciencias de la Salud, Campus Tehuacán' );
INSERT INTO institucion(id, nombre) VALUES(2 , 'Benemérita Universidad Autónoma de Puebla' );
INSERT INTO institucion(id, nombre) VALUES(3 , 'Centro de Estudios de Radiología de Durango' );
INSERT INTO institucion(id, nombre) VALUES(4 , 'Centro de Estudios Superiores en Ciencias de la Salud' );
INSERT INTO institucion(id, nombre) VALUES(5 , 'Centro de Estudios Superiores México Americano' );
INSERT INTO institucion(id, nombre) VALUES(6 , 'Centro de Estudios Universitarios Xochicalco' );
INSERT INTO institucion(id, nombre) VALUES(7 , 'Centro Educativo de Humanidades' );
INSERT INTO institucion(id, nombre) VALUES(8 , 'Centro Universitario Interamericano de Córdoba CEUNI' );
INSERT INTO institucion(id, nombre) VALUES(9 , 'Centro Universitario UNE' );
INSERT INTO institucion(id, nombre) VALUES(10 , 'Cruz Roja Mexicana Delegación Monterrey' );
INSERT INTO institucion(id, nombre) VALUES(11 , 'Escuela de Medicina Intermédica' );
INSERT INTO institucion(id, nombre) VALUES(12 , 'Escuela Superior de las Bellas Artes Chayito Garzón' );
INSERT INTO institucion(id, nombre) VALUES(13 , 'Escuela Superior de Trabajo Social Jesús Aquino Juan Subsede Tapachula' );
INSERT INTO institucion(id, nombre) VALUES(14 , 'Instituto Científico de Educación Superior' );
INSERT INTO institucion(id, nombre) VALUES(15 , 'Instituto de Ciencias y Estudios Superiores de Tamaulipas' );
INSERT INTO institucion(id, nombre) VALUES(16 , 'Instituto de Estudios Superiores de Chiapas en Tuxtla' );
INSERT INTO institucion(id, nombre) VALUES(17 , 'Instituto de Estudios Superiores del Istmo de Tehuantepec' );
INSERT INTO institucion(id, nombre) VALUES(18 , 'Instituto de Estudios Tecnológicos y Superiores Matatipac' );
INSERT INTO institucion(id, nombre) VALUES(19 , 'Instituto Dr. Carlos Coqui, Campus Zacatecas' );
INSERT INTO institucion(id, nombre) VALUES(20 , 'Instituto Educativo Hermosillo' );
INSERT INTO institucion(id, nombre) VALUES(21 , 'Instituto Intercontinental Pierre Fauchard' );
INSERT INTO institucion(id, nombre) VALUES(22 , 'Instituto Irapuato' );
INSERT INTO institucion(id, nombre) VALUES(23 , 'Instituto Politécnico Nacional' );
INSERT INTO institucion(id, nombre) VALUES(24 , 'Instituto Técnico Superior de Radiología' );
INSERT INTO institucion(id, nombre) VALUES(25 , 'Instituto Universitario de Ciencias Médicas y Humanísticas de Nayarit' );
INSERT INTO institucion(id, nombre) VALUES(26 , 'Instituto Universitario Franco Inglés de México' );
INSERT INTO institucion(id, nombre) VALUES(27 , 'Instituto Universitario Metropolitano, Campus Mexicali' );
INSERT INTO institucion(id, nombre) VALUES(28 , 'Instituto Universitario Metropolitano, Campus Tepic' );
INSERT INTO institucion(id, nombre) VALUES(29 , 'Saint Luke Escuela de Medicina' );
INSERT INTO institucion(id, nombre) VALUES(30 , 'Sistema Educativo Universitario Azteca Tuxtla / Instituto de Estudios Superiores Sor Juana Inés de la Cruz' );
INSERT INTO institucion(id, nombre) VALUES(31 , 'Universdad de Monterrey' );
INSERT INTO institucion(id, nombre) VALUES(32 , 'Universidad Americana de Acapulco' );
INSERT INTO institucion(id, nombre) VALUES(33 , 'Universidad Anáhuac Campus Norte' );
INSERT INTO institucion(id, nombre) VALUES(34 , 'Universidad Anáhuac Mayab' );
INSERT INTO institucion(id, nombre) VALUES(35 , 'Universidad Autónoma de Aguascalientes' );
INSERT INTO institucion(id, nombre) VALUES(36 , 'Universidad Autónoma de Baja California' );
INSERT INTO institucion(id, nombre) VALUES(37 , 'Universidad Autónoma de Campeche' );
INSERT INTO institucion(id, nombre) VALUES(38 , 'Universidad Autónoma de Chiapas' );
INSERT INTO institucion(id, nombre) VALUES(39 , 'Universidad Autónoma de Chihuahua' );
INSERT INTO institucion(id, nombre) VALUES(40 , 'Universidad Autónoma de Durango Campus Gómez Palacio' );
INSERT INTO institucion(id, nombre) VALUES(41 , 'Universidad Autónoma de Durango Campus Zacatecas' );
INSERT INTO institucion(id, nombre) VALUES(42 , 'Universidad Autónoma de Guadalajara' );
INSERT INTO institucion(id, nombre) VALUES(43 , 'Universidad Autónoma de Guadalajara, Campus Tabasco' );
INSERT INTO institucion(id, nombre) VALUES(44 , 'Universidad Autónoma de Nayarit' );
INSERT INTO institucion(id, nombre) VALUES(45 , 'Universidad Autónoma de Nuevo León' );
INSERT INTO institucion(id, nombre) VALUES(46 , 'Universidad Autónoma de Querétaro' );
INSERT INTO institucion(id, nombre) VALUES(47 , 'Universidad Autónoma de Sinaloa' );
INSERT INTO institucion(id, nombre) VALUES(48 , 'Universidad Autónoma de Tamaulipas' );
INSERT INTO institucion(id, nombre) VALUES(49 , 'Universidad Autónoma de Tlaxcala' );
INSERT INTO institucion(id, nombre) VALUES(50 , 'Universidad Autónoma de Zacatecas' );
INSERT INTO institucion(id, nombre) VALUES(51 , 'Universidad Autónoma del Carmen' );
INSERT INTO institucion(id, nombre) VALUES(52 , 'Universidad Autónoma del Estado de Hidalgo' );
INSERT INTO institucion(id, nombre) VALUES(53 , 'Universidad Autónoma del Estado de México' );
INSERT INTO institucion(id, nombre) VALUES(54 , 'Universidad Autónoma del Estado de Morelos' );
INSERT INTO institucion(id, nombre) VALUES(55 , 'Universidad Centroamericana' );
INSERT INTO institucion(id, nombre) VALUES(56 , 'Universidad Continente Americano, Plantel Celaya' );
INSERT INTO institucion(id, nombre) VALUES(57 , 'Universidad Cristóbal Colón' );
INSERT INTO institucion(id, nombre) VALUES(58 , 'Universidad Cuauhtémoc Plantel Aguascalientes' );
INSERT INTO institucion(id, nombre) VALUES(59 , 'Universidad Cuauhtémoc Plantel San Luís Potosí' );
INSERT INTO institucion(id, nombre) VALUES(60 , 'Universidad Cuauhtémoc, Campus Querétaro' );
INSERT INTO institucion(id, nombre) VALUES(61 , 'Universidad de Celaya' );
INSERT INTO institucion(id, nombre) VALUES(62 , 'Universidad de Ciencias de la Enfermería de México' );
INSERT INTO institucion(id, nombre) VALUES(63 , 'Universidad de Ciencias y Artes de Chiapas' );
INSERT INTO institucion(id, nombre) VALUES(64 , 'Universidad de Colima' );
INSERT INTO institucion(id, nombre) VALUES(65 , 'Universidad de Guadalajara' );
INSERT INTO institucion(id, nombre) VALUES(66 , 'Universidad de Guadalajara, Centro Universitario de los Altos' );
INSERT INTO institucion(id, nombre) VALUES(67 , 'Universidad de Guanajuato' );
INSERT INTO institucion(id, nombre) VALUES(68 , 'Universidad de Ixtlahuaca CUI' );
INSERT INTO institucion(id, nombre) VALUES(69 , 'Universidad de las Américas Puebla' );
INSERT INTO institucion(id, nombre) VALUES(70 , 'Universidad de Londres' );
INSERT INTO institucion(id, nombre) VALUES(71 , 'Universidad de Montemorelos' );
INSERT INTO institucion(id, nombre) VALUES(72 , 'Universidad de Morelia' );
INSERT INTO institucion(id, nombre) VALUES(73 , 'Universidad de Navojoa' );
INSERT INTO institucion(id, nombre) VALUES(74 , 'Universidad de Sonora' );
INSERT INTO institucion(id, nombre) VALUES(75 , 'Universidad de Zamora' );
INSERT INTO institucion(id, nombre) VALUES(76 , 'Universidad del Centro de Veracruz' );
INSERT INTO institucion(id, nombre) VALUES(77 , 'Universidad del Noreste' );
INSERT INTO institucion(id, nombre) VALUES(78 , 'Universidad del Valle de Atemajac, Campus Guadalajara' );
INSERT INTO institucion(id, nombre) VALUES(79 , 'Universidad del Valle de México Campus Hermosillo' );
INSERT INTO institucion(id, nombre) VALUES(80 , 'Universidad del Valle de México Campus Veracruz' );
INSERT INTO institucion(id, nombre) VALUES(81 , 'Universidad del Valle de Puebla, Plantel Puebla' );
INSERT INTO institucion(id, nombre) VALUES(82 , 'Universidad del Valle del Fuerte, Los Mochis' );
INSERT INTO institucion(id, nombre) VALUES(83 , 'Universidad Durango Santander Campus Hermosillo' );
INSERT INTO institucion(id, nombre) VALUES(84 , 'Universidad Guadalupe Victoria' );
INSERT INTO institucion(id, nombre) VALUES(85 , 'Universidad Hipócrates' );
INSERT INTO institucion(id, nombre) VALUES(86 , 'Universidad Juárez Autónoma de Tabasco' );
INSERT INTO institucion(id, nombre) VALUES(87 , 'Universidad Juárez del Estado de Durango' );
INSERT INTO institucion(id, nombre) VALUES(88 , 'Universidad La Concordia' );
INSERT INTO institucion(id, nombre) VALUES(89 , 'Universidad La Salle Campus San Fernando' );
INSERT INTO institucion(id, nombre) VALUES(90 , 'Universidad La Salle Oaxaca' );
INSERT INTO institucion(id, nombre) VALUES(91 , 'Universidad La Salle, Cancún' );
INSERT INTO institucion(id, nombre) VALUES(92 , 'Universidad La Salle, Noroeste' );
INSERT INTO institucion(id, nombre) VALUES(93 , 'Universidad Latina de América' );
INSERT INTO institucion(id, nombre) VALUES(94 , 'Universidad Latina de México en Celaya' );
INSERT INTO institucion(id, nombre) VALUES(95 , 'Universidad Latinoamericana, Campus Cuernavaca' );
INSERT INTO institucion(id, nombre) VALUES(96 , 'Universidad Marista de Mérida' );
INSERT INTO institucion(id, nombre) VALUES(97 , 'Universidad Marista de Valladolid' );
INSERT INTO institucion(id, nombre) VALUES(98 , 'Universidad Metropolitana de Tlaxcala' );
INSERT INTO institucion(id, nombre) VALUES(99 , 'Universidad Modelo' );
INSERT INTO institucion(id, nombre) VALUES(100 , 'Universidad Mundial' );
INSERT INTO institucion(id, nombre) VALUES(101 , 'Universidad Nacional Autónoma de México' );
INSERT INTO institucion(id, nombre) VALUES(102 , 'Universidad Pablo Guardado Chávez' );
INSERT INTO institucion(id, nombre) VALUES(103 , 'Universidad Panamericana' );
INSERT INTO institucion(id, nombre) VALUES(104 , 'Universidad para la Profesionalización Estratégica' );
INSERT INTO institucion(id, nombre) VALUES(105 , 'Universidad Popular Autónoma del Estado de Puebla' );
INSERT INTO institucion(id, nombre) VALUES(106 , 'Universidad Quetzalcoatl en Irapuato' );
INSERT INTO institucion(id, nombre) VALUES(107 , 'Universidad Regional del Sureste' );
INSERT INTO institucion(id, nombre) VALUES(108 , 'Universidad Rosaritense' );
INSERT INTO institucion(id, nombre) VALUES(109 , 'Universidad Tecnológica de México' );
INSERT INTO institucion(id, nombre) VALUES(110 , 'Universidad Teletón' );
INSERT INTO institucion(id, nombre) VALUES(111 , 'Universidad Univer Milenium, Plantel Ciencias de la Salud' );
INSERT INTO institucion(id, nombre) VALUES(112 , 'Universidad Vasco de Quiroga' );
INSERT INTO institucion(id, nombre) VALUES(113 , 'Universidad Veracruzana' );
INSERT INTO institucion(id, nombre) VALUES(114 , 'Universidad Westhill' );