imports:
  - { resource: user.yml }
  - { resource: permission.yml }
  - { resource: role.yml }
  - { resource: translate/section.yml }

easy_admin:
  design:
    menu:
      - User
      - Permission
      - Role
      - SectionTranslate
