imports:
  - { resource: user.yml }
  - { resource: permission.yml }
  - { resource: role.yml }
  - { resource: translate/section.yml }
  - { resource: catalogs/region.yml }
  - { resource: catalogs/career.yml }
  - { resource: catalogs/graduate_school.yml }
  - { resource: catalogs/delegation.yml }
  - { resource: catalogs/unit_type.yml }
  - { resource: catalogs/unit.yml }
  - { resource: catalogs/institution.yml }
  - { resource: catalogs/academic_level.yml }
  - { resource: catalogs/departament.yml }

easy_admin:
  design:
    menu:
      - User
      - Permission
      - Role
      - label: 'Catálogos'
        children:
          - Region
          - Career
          - GraduateSchool
          - Delegation
          - UnitType
          - Unit
          - Institution
          - AcademicLevel
          - Departament
      - SectionTranslate
