easy_admin:
  entities:
    Category:
      class: AppBundle\Entity\Categoria
      label: 'Categoria'
      list:
        title: 'Categoria'
        actions:
          - { name: 'new', label: 'Crear categoria' }
        fields:
          - id
          - nombre
          - clave
      form:
        fields:
          - { property: nombre, label: 'Nombre' }
          - { property: clave, label: 'Clave' }
