easy_admin:
  entities:
    Department:
      class: AppBundle\Entity\Departamento
      label: 'Departamento'
      list:
        title: 'Departamento'
        actions:
          - { name: 'new', label: 'Crear departamento' }
        fields:
          - id
          - nombre
          - { property: claveDepartamental, label: 'Clave departamental' }
          - { property: clavePresupuestal, label: 'Clave presupuestal' }
          - { property: unidad.nombre, label: 'Unidad' }
          - { property: esUnidad, label: 'Es unidad', type: toggle }
          - { property: anio, label: 'Año' }
          - { property: fecha, label: 'Fecha' }
          - { property: activo, type: toggle }
      form:
        fields:
          - { property: nombre, label: 'Nombre' }
          - { property: claveDepartamental, label: 'Clave departamental' }
          - { property: clavePresupuestal, label: 'Clave presupuestal' }
          - { property: unidad, label: 'Unidad', type: entity, type_options: { choice_label: 'nombre' } }
          - { property: esUnidad, label: 'Es unidad' }
          - { property: anio, label: 'Año' }
          - activo
