easy_admin:
  entities:
    Institution:
      class: AppBundle\Entity\Institucion
      label: 'Institución'
      search:
        fields: [ 'nombre', 'convenios.delegacion.nombre', 'correo' ]
      list:
        title: 'Institución'
        actions:
          - { name: 'new', label: 'Crear institución' }
        fields:
          - id
          - { property: delegacionesToString, label: 'OOAD Convenio' }
          - nombre
          - { property: telefono, label: 'Teléfono' }
          - correo
          - fax
          - sitioWeb
          - { property: rfc, label: 'RFC' }
          - { property: direccion, label: 'Dirección' }
      form:
        fields:
          - nombre
          - { property: telefono, label: 'Teléfono' }
          - correo
          - fax
          - sitioWeb
          #- { property: 'cedulaFile', type: 'vich_file', label: 'Cédula de identificación' }
          - { property: rfc, label: 'RFC' }
          - { property: direccion, label: 'Dirección' }
