<?php

namespace AppBundle\Repository;

/**
 * CampoClinicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoClinicoRepository extends \Doctrine\ORM\EntityRepository
{
}
