<?php

namespace AppBundle\Repository;

/**
 * estatus_campoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class estatus_campoRepository extends \Doctrine\ORM\EntityRepository
{
}
