<?php

namespace AppBundle\Repository;

/**
 * EstatusCampoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstatusCampoRepository extends \Doctrine\ORM\EntityRepository
{
}
