<?php

namespace AppBundle\Repository;

use AppBundle\DTO\TraductorDTO;
use Doctrine\ORM\Mapping;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslateRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTextsByLocale($locale)
    {
        $translate = $this->findOneBy(['locale' => $locale]);

        if($translate === null) {
            return $translate;
        }

        $encoders = [new JsonEncoder()];
        $normalizers = [new ObjectNormalizer()];
        $serializer = new Serializer($normalizers, $encoders);

        $traductorDTO = $serializer->deserialize(
            $translate->getTextos(),
            TraductorDTO::class,
            'json'
        );
        $translate->setTraductorDTO($traductorDTO);

        return $translate;
    }
}
