<?php

namespace AppBundle\Controller\Admin\Translation;

use AppBundle\Entity\Translation\Category;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AdminController as BaseAdminController;

class CategoryTranslation extends BaseAdminController
{
    /**
     * @param  \AppBundle\Entity\Translation\CategoryTranslation $categoryTranslation
     */
    protected function prePersistEntity($categoryTranslation)
    {
        $category = $this->getDoctrine()
            ->getRepository(Category::class)
            ->findOneBy(['modulo' => $categoryTranslation->getModulo()]);

        if($category === null) $category = new Category();

        $category->setModulo($categoryTranslation->getModulo());
        $categoryTranslation->setTranslatable($category);
        $category->mergeNewTranslations();
    }

    /**
     * @param \AppBundle\Entity\Translation\CategoryTranslation $entity
     * @return \Symfony\Component\Form\Form
     */
    protected function createEditForm($entity, array $entityProperties)
    {
        $entity->setModulo(
            $entity->getTranslatable()->getModulo()
        );
        return parent::createEditForm($entity, $entityProperties); // TODO: Change the autogenerated stub
    }


}
