<?php

namespace AppBundle\Controller\Admin\Translation;

use AppBundle\Entity\Translation\Seccion;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AdminController as BaseAdminController;

class SectionTranslation extends BaseAdminController
{
    /**
     * @param  \AppBundle\Entity\Translation\SeccionTranslation $entity
     */
    protected function prePersistEntity($entity)
    {
        $text = $this->getDoctrine()
            ->getRepository(Seccion::class)
            ->findOneBy(['modulo' => $entity->getModulo()]);

        if($text === null) $text = new Seccion();

        $text->setModulo($entity->getModulo());
        $entity->setTranslatable($text);
        $text->mergeNewTranslations();
    }

    /**
     * @param \AppBundle\Entity\Translation\SeccionTranslation $entity
     * @return \Symfony\Component\Form\Form
     */
    protected function createEditForm($entity, array $entityProperties)
    {
        $entity->setModulo(
            $entity->getTranslatable()->getModulo()
        );

        return parent::createEditForm($entity, $entityProperties); // TODO: Change the autogenerated stub
    }
}
