imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        dbname: '%database_name%-test'
#doctrine:
#    dbal:
#        default_connection: default
#        connections:
#            default:
#                driver:   pdo_sqlite
#                path:     %kernel.cache_dir%/test.db

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../tests/AppBundle/Migrations"
    namespace: Tests\AppBundle\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false
