imports:
    - { resource: config_dev.yml }

parameters:
    app.path.instituciones: /tests/uploads/files/instituciones

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        dbname: '%database_name%-test'
#doctrine:
#    dbal:
#        default_connection: default
#        connections:
#            default:
#                driver:   pdo_sqlite
#                path:     %kernel.cache_dir%/test.db

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../tests/AppBundle/Migrations"
    namespace: Tests\AppBundle\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false

vich_uploader:
    db_driver: orm
    mappings:
        institucion_cedulas:
            uri_prefix: '%app.path.instituciones%'
            upload_destination: '%kernel.root_dir%/../web/tests/uploads/files/instituciones'
            namer: AppBundle\Vich\Naming\CedulaNamer
            directory_namer: app.directory_namer.comprobantepago
        pagos:
            uri_prefix: '%app.path.instituciones%'
            upload_destination: '%kernel.root_dir%/../web/tests/uploads/files/instituciones'
            namer: AppBundle\Vich\Naming\ComprobantePagoNamer
            directory_namer: app.directory_namer.comprobantepago
