app_secret: "{{ vault_app_secret }}"
database_user: "{{ vault_database_user }}"
database_password: "{{ vault_database_password }}"
database_name: "{{ vault_database_name }}"
database_url: "pgsql://{{ database_user }}:{{ database_password }}@localhost/{{ database_name }}"
aws_ses_username: "{{ vault_aws_ses_username }}"
aws_ses_password: "{{ vault_aws_ses_password }}"
aws_ses_server_name: "{{ vault_aws_ses_server_name }}"
mailer_url: "smtp://{{ aws_ses_server_name }}?encryption=tls&username={{ aws_ses_username }}&password={{ aws_ses_password }}"
mailer_user: "{{ vault_mailer_user }}"
amazon_s3_key: "{{ vault_amazon_s3_key }}"
amazon_s3_secret: "{{ vault_amazon_s3_secret }}"
amazon_s3_bucket: "{{ vault_amazon_s3_bucket }}"
amazon_s3_region: "{{ vault_amazon_s3_region }}"
amazon_s3_version: "{{ vault_amazon_s3_version }}"
